# Generated by Django 2.0.5 on 2018-05-08 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'DNI inválido.')])),
                ('complete_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
